name: Back test aws

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: aws-back
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check
        run: ls
      - name: Pulling project
        run: git pull
      - name: Stopping containers
        run: sudo docker compose down
      - name: Delete image
        run: sudo docker image rm img-carbook-backend
      - name: Building image
        run: sudo docker image build -t img-carbook-backend .
      - name: Upping containers
        run: sudo docker compose up -d
